repos:
-   repo: https://github.com/ambv/black
    rev: 19.3b0
    hooks:
    - id: black
      language_version: python3.7
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    - id: flake8
    - id: trailing-whitespace
      files: \.(js|rb|md|py|sh|txt|yaml|yml)$
    - id: check-yaml
      files: \.(yaml|yml)$
    - id: check-merge-conflict
      files: \.(js|rb|md|py|sh|txt|yaml|yml)$
    - id: check-symlinks
    - id: end-of-file-fixer
